---
title: "HW 7 Group"
author: "Hallie Trial"
date: "7/13/2021"
output: html_document
---


## Creating the database and connecting to it:
```{r}
library(RSQLite)
dcon <-dbConnect(SQLite(), dbname = "Data/finalproject.sqlite")
```


## Adding county presidential data and paring down to a more manageable table containing only the years we need:
```{r}
table <- read.csv("Data/countypres_2000-2020.csv")
dbWriteTable(conn = dcon, name = "countypres", table,
             append = TRUE, row.names = FALSE)


query <- "
CREATE TABLE countypres_2016_2020 AS
SELECT *
FROM countypres
WHERE year = 2020 OR year = 2016;"
dbSendQuery(dcon, query)

dbListTables(dcon)


query <- paste0("
SELECT *	
FROM countypres_2016_2020;")
res <- dbSendQuery(dcon, query)
presdf <- dbFetch(res, -1)
head(presdf)

dbClearResult(res)

```


## Adding the vaccination data:
```{r}
table <- read.csv("Data/COVID-19_vaccination/data_tables/vaccine_data/us_data/time_series/people_vaccinated_us_timeline.csv")
dbWriteTable(conn = dcon, name = "vaccination", table,
             append = TRUE, row.names = FALSE)


query <- paste0("
SELECT *	
FROM vaccination;")
res <- dbSendQuery(dcon, query)
vaccdf <- dbFetch(res, -1)
head(vaccdf)

dbClearResult(res)


dbListTables(dcon)


```


## Adding cases data and paring down to a more manageable table containing only the year we need:
```{r}
table <- read.delim("Data/county_cases.txt", header = TRUE, sep = ",", dec = ".")
dbWriteTable(conn = dcon, name = "cases", table,
             append = TRUE, row.names = FALSE)


query <- "
CREATE TABLE cases2021 AS
SELECT *
FROM cases
WHERE date LIKE '___1%';"
dbSendQuery(dcon, query)



query <- paste0("
SELECT *	
FROM cases2021;")
res <- dbSendQuery(dcon, query)

casedf <- dbFetch(res, -1)
head(casedf)

dbClearResult(res)


dbListTables(dcon)

dbDisconnect(dcon)

```

