## Discussion

### Summary of findings

1. Among broad geographic regions of the nation, the Northeast has highest mean vaccination and tightest distribution, followed by the Midwest and West, while the South is lagging significantly behind the rest of the country in vaccination levels.
2. Counties in the South were more likely to have higher ratios of cases and deaths per 100,000 people to vaccination rates than were counties in the Northeast, Midwest, or West, suggesting that severity and vaccination levels might not be positively correlated or correlated at all.
3. Generally, much of the South exhibited high levels of vaccine hesitancy and much of the Northeast exhibited very low levels of vaccine hesitancy, inversely mirroring the trends in vaccination levels as expected. However, Texas had surprisingly low levels of vaccine hesitancy, as did Nebraska, Utah, and the Dakotas.
4. Counties in more vulnerable SVI categories had, on average, lower vaccination rates, and this difference was statistically significant.
5. The distribution of vaccination rates among counties in vulnerable SVI categories had a small peak at very low vaccination rates, indicating the possible existence of a subgroup of vulnerable counties in which vaccination rates are controlled by another factor.
6. The percentage of a county's votes in the 2020 presidential election cast for Trump was negatively correlated with the county's vaccination levels.
7. Among outlier counties in which vaccination levels were not well-predicted by political leanings, outliers with lower-than-predicted vaccination levels had higher average proportion Black populations than outliers with higher-than-predicted vaccination levels of the same political leaning and were more likely to have larger Black populations.
8. For Democratic counties in which Black residents make up more than 5% of the population, vaccine hesitancy was positively correlated with race.
9. Very High, High, or Moderate Vulnerability counties (by SVI) with very low vaccination rates (<15%) were much more likely to have higher percentage Black populations than their higher vaccination counterparts with the same SVI values, while the difference between very low vaccination rate counties and their more vaccinated counterparts among Low and Very Low Vulnerability counties was far less pronounced.
10. Counties hit harder by the pandemic (counties with large numbers of cumulative deaths per 100,000 residents) do not seem to have significantly higher vaccination rates.

### Analysis and Recommendations

#### Death rates

##### Politics

There was a definitive negative correlation between the percentage of votes cast for Trump in the 2020 presidential election and county vaccination rate. This parallels a trend of conservative media coverage questioning the safety, efficacy, and necessity of Covid vaccination. As an extreme example, on July 27, conservative Fox show host Tucker Carlson compared the Covid-19 vaccine to "sterilization or frontal lobotomies" and pointed to rising cases in the US as evidence that “a rational person would assume there is something wrong with the vaccines," even though vaccines have shown to be effective at preventing infection and extremely effective at preventing serious illness and death.

There is hope that this trend could change, however. Recently, a growing number of conservative elected officials and media outlets have begun to speak out in favor of vaccination. Fox News has launched a public service announcement urging viewers to get vaccinated. On July 23, Republican governor of Alabama Kay Ivey urged her state to get vaccinated and called vaccines "the greatest weapon we have to fight Covid." In the same week, the Republican governor of Florida, Ron DeSantis, stated that "these vaccines are saving lives" and Senate minority leader Mitch McConnell said, “These shots need to get in everybody’s arms as rapidly as possible, or we're going to be back in a situation in the fall that we don’t yearn for.” Our results suggest that vaccine outreach should be heavily targeted towards high-risk conservative communities, and Republican public officials could perhaps be the most effective mouthpiece; more Republican leaders, especially Trump, around the nation should follow the examples of Ivey, DeSantos, McConnell, and others in strongly endorsing the COVID-19 vaccine.

##### Race

Throughout our report, the proportion of a county's population that identified as Black repeatedly emerged as a factor related to COVID-19 vaccination levels. It is important to disambiguate the influence of supply and demand on county vaccination levels to determine what strategies health officials can use to promote COVID-19 vaccination in lagging communities. We tentatively hypothesize that the relationship between race and vaccination results from higher levels of vaccine hesitancy among Black Americans because among predominately Democratic counties, we observed a correlation between percent Black residents and vaccine hesitancy. 

Unfortunately, these results are unsurprising and echo other reports. In a survey by the CDC in December 2020, for instance, 46% of Black adults in the US stated that they probably would not choose to receive the COVID-19 vaccine, compared with 30% of white adults. Many have argued that vaccine hesitancy manifests a deeper distrust of modern medicine within Black American communities motivated by the historically exploitative relationship between medical science and Black patients. Notorious examples include the Tuskegee Syphilis Study, in which investigators withheld treatment from Black study subjects for decades; the harvesting of Henrietta Lacks's cancer cells to create a cell line for medical research without her (or or family's) consent or knowledge; and forced sterilization of Black women mandated by the North Carolina Eugenics Board.

Stronger outreach to vulnerable and historically mistreated communities is a key tool in vaccinating the American public.

##### Region

Ultimately, our analysis of ratios of case and death rates to vaccination levels, as well as of just vaccination levels and hesitancy, suggests that there is clearly some relationship between region and these data. Throughout the analysis, we see that the South has much worse ratio values than the rest of the country, especially as compared to the Northeast. Additionally, while the South and Northeast were at opposite ends of the spectrum, the Midwest and West exhibited far more middle-of-the-road ratio values and had a wide range of vaccination and ratio levels across counties. 

While it may be tempting to then say geography is a strong determining factor in predicting these ratios and levels, it is in fact incorrect to do so. While there certainly seems to be a correlation, we know that geography is closely related to race and vulnerability levels, and especially to political views. As such, we cannot say just from looking at a regional analysis that geography by itself is an important factor rather than an indicator of the presence of another variable property that might in fact be the real reason or a more important reason for certain trends in the data.
