---
title: "HW 8 group"
author: "Prayag Gordy"
date: "7/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
											message = FALSE,
											warning = FALSE)
```

```{r}
library(magrittr); library(RSQLite); library(ggplot2)

config <- yaml::read_yaml("../config.yaml")

covid <- readr::read_csv(paste0("../", config$paths$raw, config$data$nyt_covid))
vaccination <- readr::read_csv(paste0("../", config$paths$us_ts, config$data$vax_data_ts))
```

### Problem 1

```{r}
df <- covid %>% 
	dplyr::filter(state == "Maryland") %>% 
	dplyr::group_by(date) %>% 
	dplyr::summarize(cases = sum(cases, na.rm = T)) %>% 
	dplyr::ungroup() %>% 
	dplyr::mutate(date = as.Date(date)) %>% 
	dplyr::select(date, Cases = cases) %>% 
	dplyr::inner_join(vaccination %>% 
											dplyr::filter(Province_State == "Maryland",
																		Vaccine_Type == "All") %>% 
											dplyr::select(date = Date, Doses = Doses_admin) %>% 
											dplyr::mutate(date = as.Date(date)),
										by = "date") %>% 
	dplyr::mutate(dplyr::across(c(Cases), ~. - dplyr::lag(.))) %>%
	tidyr::drop_na() %>% 
	tidyr::pivot_longer(cols = c(Cases, Doses))

ggplot(df, aes(x = date, y = value, color = name)) +
	geom_line(size = 1, alpha = 0.8) +
	theme_minimal() +
	facet_wrap(~ name, scales = "free_y", ncol = 1) +
	labs(x = "Date",
			 y = "Number of people",
			 title = "<span style='color:#ab2207'>New cases</span> and <span style='color:#5461b0'>cumulative vaccine doses</span> in Maryland") +
	theme(plot.title = ggtext::element_markdown(),
				legend.title = element_blank()) +
	scale_color_manual(values = c("Cases" = "#ab2207", "Doses" = "#5461b0")) + 
	scale_y_continuous(labels = scales::comma) +
	scale_x_date(date_labels = "%B")
```


### Problem 2

```{r}
lu_fips <- tidycensus::fips_codes %>% 
	dplyr::mutate(county_name = stringr::str_replace_all(county, " County", ""))

head(lu_fips)

paste("The longest county name is", max(stringr::str_length(lu_fips$county)), "characters, including the word 'County.' We will have to account for this when labeling counties in our graphs.")
```

