paths:
  raw: "data/raw/"
  proc: "data/processed/"
  plots: "plots/"
  us_hr: "data/raw/us_data/hourly"
  us_ts: "data/raw/us_data/time_series"
  global_data: "data/raw/global_data"

data:
  nyt_covid: "nyt_covid.csv"
  db: "finalproject.db"
  pres: "countypres_2000-2020.csv"
  global_doses: "time_series_covid19_vaccine_doses_admin_global.csv"
  global_vax: "time_series_covid19_vaccine_global.csv"
  global_vax_data: "vaccine_data_global.csv"
  vax_data: "vaccine_data_us.csv"
  ppl_vax: "vaccine_people_vaccinated_US.csv"
  ppl_vax_ts: "people_vaccinated_us_timeline.csv"
  doses: "time_series_covid19_vaccine_doses_admin_US.csv"
  vax_data_ts: "vaccine_data_us_timeline.csv"
  census: "census.csv"

