libraries: ["magrittr", "RSQLite", "tidyverse", "tidycensus", "tigris", "knitr",
            "kableExtra", "broom", "MASS", "grid", "readr", "gridExtra"]

paths:
  raw: "data/raw/"
  proc: "data/processed/"
  plots: "plots/"
  rmd: "Rmd/"

data:
  nyt_covid: "nyt_covid.csv"
  db: "finalproject.db"
  pres: "countypres_2000-2020.csv"
  cdc_vacc: "COVID-19_Vaccinations_in_the_United_States_County.csv"
  vacc_hes: "Vaccine_Hesitancy_for_COVID-19__County_and_local_estimates.csv"
  tex_vacc: "people_vaccinated_tx.csv"
  va_vacc: "va_vacc.csv"
  small_ca_vacc: "manual_CA_smallcounty_vacc.csv"
  vax_data_all: "vaccine_data_us_full.csv"
  census: "{geography}_census.csv"
  region_xwalk: "region_xwalk.csv"
  tx_fips: "txfips.csv"

urls:
  nyt_covid: "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"
  region_xwalk: "https://raw.githubusercontent.com/cphalpert/census-regions/master/us%20census%20bureau%20regions%20and%20divisions.csv"
  cdc_vacc: "https://data.cdc.gov/api/views/8xkx-amqh/rows.csv?accessType=DOWNLOAD"
  tex_vacc: "https://www.dshs.texas.gov/immunize/covid19/COVID-19-Vaccine-Data-by-County.xls"
  va_vacc: "https://data.virginia.gov/api/views/28k2-x2rj/rows.csv?accessType=DOWNLOAD"
  vacc_hes: "https://data.cdc.gov/api/views/q9mh-h2tw/rows.csv?accessType=DOWNLOAD"

census:
  vars: {med_income: "B19013_001", male: "B01001_002",
         female: "B01001_026", med_age: "B01002_001",
         white: "B01001A_001", black: "B01001B_001",
         hispanic: "B01001I_001", asian: "B01001D_001",
         total: "B01001_001", other: "B01001F_001"}

paper:
  sections: ["introduction", "data", "results", "discussion", "appendix"]

charts:
  cols:
    svi: ["#f80808", "#eb7606", "#ded904", "#71d003", "#0bc202"]

states_remove: ["02", "15"]  # Alaska and Hawaii

maps:
  scale_breaks:
    fully_vax:
      cuts: [0.25, 0.45, 0.65]
      labels: ["< 25%", "25-45%", "45-65%", "> 65%"]
    cases_fully_vax:
      cuts: [23000, 30000, 39000]
      labels: ["< 23,000", "23,000-30,000", "30,000-39,000", "> 39,000"]
    deaths_fully_vax:
      cuts: [300, 550, 800]
      labels: ["< 300", "300-500", "500-800", "> 800"]
    hesitant_unsure:
      cuts: [0.15, 0.2, 0.25]
      labels: ["< 15%", "15-20%", "20-25%", "> 25%"]
  fills:
    cols: ["red4", "red1", "steelblue2", "blue2"]
    rev:
      fully_vax: FALSE
      cases_fully_vax: TRUE
      deaths_fully_vax: TRUE
      hesitant_unsure: TRUE
  cns:
    fully_vax: "Fully vaccinated proportion"
    cases_fully_vax: "Cases per 100,000 weighted by vaccination rate"
    deaths_fully_vax: "Deaths per 100,000 weighted by vaccination rate"
    hesitant_unsure: "Vaccine hesitancy"
